mockingbird/mockingbird/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # path('twitter/', include('twitter.urls')),
    path(r'', include('twitter.urls')),
    # path('mockingbird.hip.cat/', include('twitter.urls')),
    path('admin/', admin.site.urls),
]

mockingbird/twitter/urls.py
from django.urls import path

from . import views, view_info, view_edit, view_explain

app_name = 'twitter'
urlpatterns = [
    path('', views.index, name='index'),
    path('username/', views.username, name='username'),
    path('<username>/tweets/', views.tweets, name='tweets'),
    path('<username>/profile/', views.profile, name='profile'),
    path('<username>/profile/reset/', views.reset_tweets, name='reset_tweets'),
    path('<username>/ibm/info/', view_info.ibm_info, name='ibm_info'),
    path('<username>/<attr>_m3/info/', view_info.m3_info, name='m3_info'),
    path('<username>/<attr>_blob/info/', view_info.blob_info, name='blob_info'),
    path('<username>/<attr>_clf/info/', view_info.clf_info, name='clf_info'),
    path('<username>/<attr>/info/', view_info.lex_info, name='lex_info'),
    path('<username>/<attr>_lex/edit/<target>/', view_edit.lex_edit, name='lex_edit'),
    path('<username>/<attr>_lime/edit/<target>/', view_edit.lime_edit, name='lime_edit'),
    path('<username>/<attr>_lex/edited/', views.lex_edited, name='lex_edited'),
    path('<username>/<attr>_lime/edited/', views.lime_edited, name='lime_edited'),
    path('<username>/<attr>_lime/explanation/', view_explain.lime_explain, name='lime_explanation'),
    path('<username>/<attr>_lime/explain_all/', view_explain.lime_explain_all, name='lime_explain_all')
]

mockingbird/twitter/forms.py
from django import forms


class UsernameForm(forms.Form):
    username = forms.CharField(label='', max_length=100, widget=forms.TextInput(
        attrs={'type': 'text_form', 'name': 'username', 'placeholder': "Enter username"}))
    no_tweets = forms.IntegerField(label='', initial=200, widget=forms.NumberInput(
        attrs={'type': 'integer_form', 'name': 'no_tweets', 'placeholder': "Number of Tweets"}
    ))
    use_sensitive = forms.BooleanField(label='', initial=False, required=False, widget=forms.CheckboxInput())

    # Return username as a string
    def get_username(self):
        return str(self.fields['username'])


class UpdateTweetForm(forms.Form):
    tweet_1 = forms.CharField(required=False, label='Tweet 1',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_1'}))
    tweet_2 = forms.CharField(required=False, label='Tweet 2',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_2'}))
    tweet_3 = forms.CharField(required=False, label='Tweet 3',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_3'}))
    tweet_4 = forms.CharField(required=False, label='Tweet 4',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_4'}))
    tweet_5 = forms.CharField(required=False, label='Tweet 5',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_5'}))
    tweet_6 = forms.CharField(required=False, label='Tweet 6',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_6'}))
    tweet_7 = forms.CharField(required=False, label='Tweet 7',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_7'}))
    tweet_8 = forms.CharField(required=False, label='Tweet 8',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_8'}))
    tweet_9 = forms.CharField(required=False, label='Tweet 9',
                              widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_9'}))
    tweet_10 = forms.CharField(required=False, label='Tweet 10',
                               widget=forms.Textarea(attrs={'type': 'text_form', 'name': 'tweet_10'}))
    target_class = forms.CharField(required=True, label='target', widget=forms.HiddenInput())
    start_index = forms.IntegerField(required=True, label='start_index', widget=forms.HiddenInput())

mockingbird/twitter/views.py
from django.shortcuts import render
from .forms import UsernameForm
from .models import Tweet, Profile, build_tweet, User
from .profile_builders import *
from classifiers.get_tweets import read_tweets, get_tweets
from twitter.view_edit import save_tweets, lex_edit, lime_edit
from twitter.view_explain import lime_explain

from twitter.view_helper_functions import clear_and_build_profile


# Collect username
def index(request):
    form = UsernameForm()

    return render(request, 'twitter/index.html', {'form': form})


# Get Tweets for username and display. A wrapper for tweets.
def username(request):
    username = request.POST['username']
    tweet_limit = int(request.POST['no_tweets'])
    use_sensitive = False
    if 'use_sensitive' in request.POST:
        use_sensitive = bool(request.POST['use_sensitive'])

    # Check to see if the username already exists
    try:
        u = User.objects.get(username=username)
        u.tweet_limit = tweet_limit
        u.use_sensitive = use_sensitive
    except Exception:
        u = User(username=username, tweet_limit=tweet_limit, use_sensitive=use_sensitive)
    u.save()
    return tweets(request, username)


# Load and display Tweets
def tweets(request, username, recalculate=False):

    # Scrape new tweets and return
    def scrape(request, user):
        # Deactivate any existing Tweets
        tweets = Tweet.objects.filter(username=user.username, is_active=True)
        if tweets:
            for t in tweets:
                t.is_active = False
                t.save()

        # Scrape Tweets
        get_tweets(username, save_csv=True, local=False, limit=user.tweet_limit)
        tweets = read_tweets('./classifiers/data/twint_data/' + str(username) + '.csv')
        new_tweets = []
        for tweet in tweets:
            new_tweets.append(build_tweet(username, tweet))
        tweet_count = len(new_tweets)
        user.scraped_tweets = tweet_count
        user.save()
        return render(request, 'twitter/username.html', {'username': username, 'tweets': tweets})

    # Attempt to read Tweets from database
    user = User.objects.get(username=username)

    # If this is the test user, load their tweets
    if user.username == 'test':
        tweets = Tweet.objects.filter(username=username, is_active=True)
        if tweets and not recalculate:
            tweets = [x.tweet for x in tweets]
        else:
            tweets = read_tweets('./classifiers/data/test.csv')
            for tweet in tweets:
                build_tweet(username, tweet)
        return render(request, 'twitter/username.html', {'username': username, 'tweets': tweets})

    # If we haven't scraped yet, or if we've already scraped but scraped too few, scrape more
    if user.scraped_tweets == -1 or (user.scraped_tweets % 20 == 0 and user.tweet_limit > user.scraped_tweets):
        return scrape(request, user)

    # Otherwise, see if we have any existing tweets
    tweets = Tweet.objects.filter(username=username, is_active=True)
    if tweets and not recalculate:
        t = [x.tweet for x in tweets]
        return render(request, 'twitter/username.html', {'username': username, 'tweets': t})
    else:
        # Attempt to read from csv file
        try:
            # If we find the file, read it, add it to the database, and proceed
            tweets = read_tweets('./classifiers/data/twint_data/' + str(username) + '.csv')
            for tweet in tweets:
                build_tweet(username, tweet)
            return render(request, 'twitter/username.html', {'username': username, 'tweets': tweets})

        except FileNotFoundError:
            return scrape(request, user)


# Display profile.
def profile(request, username, recalculate=False):
    # Check if values for each classifier exist. If they don't, build them.

    # Try lexical classifiers.

    # Try gender first.
    lex_gender = clear_and_build_profile(username, 'gender', recalculate)

    # Try age next
    lex_age = clear_and_build_profile(username, 'age', recalculate)

    # Try sentiment next
    lex_sent = clear_and_build_profile(username, 'sentiment', recalculate)

    # Try IBM (Big Five)
    ibm = clear_and_build_profile(username, 'ibm', False)  # This is to reduce API calls while testing

    # Try M3: age, gender, is_organization
    m_gen, m_age, m_corp = clear_and_build_profile(username, 'm3', False)  # Recalculate doesn't matter here

    # Try textblob
    tb_sen1, tb_subj, tb_sen2 = clear_and_build_profile(username, 'blob', recalculate)

    # Try classifier results
    inc_reg, inc_cat, edu, relationship, sensitive = clear_and_build_profile(username, 'clf', recalculate)

    gender = [lex_gender, m_gen]
    age = [lex_age, m_age]
    income = [inc_reg, inc_cat]
    education = [edu]
    rel = [relationship]

    sent = [lex_sent, tb_sen1, tb_sen2]
    subj = [tb_subj]
    ibm = ibm
    corp = [m_corp]

    if sensitive is None:
        classes = [sent, gender, age, income, rel, education, subj, corp]
    else:
        classes = [sent, gender, age, income, rel, [sensitive[0]], [sensitive[1]], [sensitive[2]], education, subj,
                   corp]

    # Return all results
    return render(request, 'twitter/profile.html', {'username': username, "classes": classes,
                                                    "ibm": ibm})


# Reset Tweets to the originals (read from csv file)
def reset_tweets(request, username):

    # Deactivate all current Tweets and previous served
    new_tweets = Tweet.objects.filter(username=username, is_active=True)
    for t in new_tweets:
        t.is_active = False
        t.save()

    # Read and save new Tweets
    if username != 'test':
        tweets = read_tweets('./classifiers/data/twint_data/' + str(username) + '.csv')
    else:
        tweets = read_tweets('./classifiers/data/test.csv')
    for tweet in tweets:
        _ = build_tweet(username, tweet)
    return profile(request, username, recalculate=True)


# Handle loading profiles and edited pages after receiving edits
def lex_edited(request, username, attr):
    target = request.POST['target']
    if 'next' in request.POST:
        value = 'next'
        prev_index = int(request.POST['start_index'])
    elif 'prev' in request.POST:
        value = 'prev'
        prev_index = int(request.POST['start_index'])
    else:
        value = 'profile'
        prev_index = -1

    # Save any Tweets from the form to the database.
    tweets = []
    for i in range(1, 11):
        tweets.append(request.POST['tweet_' + str(i)])

    is_changed = save_tweets(username, tweets, 'lex-' + target)

    # If we saw changes, clear the old profiles as they need to be recalculated
    if is_changed:
        profiles = Profile.objects.filter(username=username, is_current=True)
        for p in profiles:
            p.is_current = False
            p.save()

    if value == 'profile':
        return profile(request, username, recalculate=is_changed)
    elif value == 'prev':
        if attr in ['polarity', 'subjectivity']:
            attr_p = 'blob'
        else:
            attr_p = attr
        # Build new profiles
        clear_and_build_profile(username, attr_p, is_changed)
        # Return previous 10 Tweets
        return lex_edit(request, username, attr, target, prev_index - 1)
    else:
        if attr in ['polarity', 'subjectivity']:
            attr_p = 'blob'
        else:
            attr_p = attr
        # Move on to the next 10 Tweets to edit
        clear_and_build_profile(username, attr_p, is_changed)
        return lex_edit(request, username, attr, target, prev_index + 1)


# Handle loading profiles and edited pages after receiving edits
def lime_edited(request, username, attr):
    target = request.POST['target']
    if 'next' in request.POST:
        value = 'next'
        prev_index = int(request.POST['next'])
        tweet_id = -1
    elif 'prev' in request.POST:
        value = 'prev'
        prev_index = int(request.POST['prev'])
        tweet_id = -1
    elif 'tweet' in request.POST:
        value = 'explain'
        tweet_id = int(request.POST['tweet'])
        prev_index = int(request.POST['start_index'])
    elif 'return' in request.POST:
        value = 'return'
        tweet_id = -1
        prev_index = int(request.POST['start_index'])
    else:
        value = 'profile'
        prev_index = -1
        tweet_id = -1

    # Save any Tweets from the form to the database.
    if 'tweet_2' in request.POST:
        tweets = []
        for i in range(1, 11):
            tweets.append(request.POST['tweet_' + str(i)])
    else:
        tweets = [request.POST['tweet_1']]

    is_changed = save_tweets(username, tweets, 'lime-' + attr + '-' + target)

    # If we saw changes, clear the old profiles as they need to be recalculated
    if is_changed:
        profiles = Profile.objects.filter(username=username, is_current=True)
        for p in profiles:
            p.is_current = False
            p.save()

    if value == 'profile':
        return profile(request, username, recalculate=is_changed)
    # Return to pages to edit Tweets
    elif value in ['prev', 'next', 'return']:
        if attr == 'nbc':
            attr_p = 'blob'
        elif attr in ['education', 'income', 'income (categorical)', 'relationship', 'religion', 'race', 'politics']:
            attr_p = 'clf'
        else:
            attr_p = attr
        # Build new profiles
        clear_and_build_profile(username, attr_p, is_changed)
        if value == 'next':
            next_index = prev_index + 1
        elif value == 'prev':
            next_index = prev_index - 1
        else:
            next_index = prev_index
        return lime_edit(request, username, attr, target, next_index)
    elif value == 'explain':
        return lime_explain(request, username, attr, request.POST['tweet_' + str(tweet_id)], target, prev_index)
    else:
        raise Exception("Unexpected field %s" % value)

mockingbird/twitter/templates/twitter/blob_info.html
<head>
    {% load static %}
    {% load multifor %}
    {% load twitter_tags %}
    <link rel="stylesheet" type="text/css" href="/static/twitter/style.css?{% now 'U' %}">
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js"></script>
    {{script|safe}}
</head>
<body>
    {% if attr == 'polarity' %}
    <div><strong>Text Sentiment (Pattern)</strong></div>
    {% elif attr == 'nbc' %}
    <div><strong>Text Sentiment (Naive Bayes Classifier)</strong></div>
    {% else %}
    <div><strong>Text Subjectivity</strong></div>
    {% endif %}
    <br>
        <div class="lexicon">
        <div class="lex_column">
    {{paragraphs.0}}
    <br>
            <br>
        {{paragraphs.1}}
            </div>
    <div class="class_plot" align="center" style="font-size:5px;">{{ div|safe }}</div>
    </div>
    <br>
    <br>
        {% if attr == 'nbc' %}
    <strong>Confidence That Your Profile is Positive: {% float_to_percent classifier.class_confidence %}</strong>
        <br>
        <br>
    <br>
    {% endif %}
    <a class="page_button" href="{% url 'twitter:profile' username%}">Take me back to my profiles</a>
    <br>
    <br>
    {% if attr == 'nbc' %}
    <span>Click this button to generate an explanation for your profile. This may take several minutes.</span>
    <a class="page_button" href="{% url 'twitter:lime_explain_all' username attr %}">Explain my profile</a>
    {% endif %}
    <br>
    <br>
    <br>
    <div style="font-size:16px;text-align:left;">
    {{paragraphs.2}}
    </div>
    <br>
        <div class="lex_exp">
        <div class="lex_column">
            {% if attr != 'nbc' %}
        <strong>{{adjs.4|title}} Words with Weights:</strong>
        <br>
        {% get_explanations classifier 1 True dec as wordlist%}
        {% for word in wordlist %}
        {{forloop.counter}}) {{word.0}}, {{word.1}}
        <br>
        {% endfor %}
            {% endif %}
        <br>
        <strong>{{adjs.4|title}} Tweets:</strong>
        <br>
        {% order_and_return classifier 5 as tweet_list %}
        {% for tweet in tweet_list|slice:":5" %}
            {% autoescape off %}
        {% add_tag tweet.0 tweet.1 'strong' as to_print%}
        {{forloop.counter}}) {{to_print}}
            {% endautoescape %}
        <br>
        {% endfor %}
        <br>
            <br>
        <br>
            {% if attr != 'nbc' %}
        <a class="page_button" href="{% url 'twitter:lex_edit' username attr adjs.0 %}">Make my profile {{adjs.2}}</a>
            <br>
            <br>
            {% else %}
            <a class="page_button" href="{% url 'twitter:lime_edit' username attr adjs.0 %}">Make my profile {{adjs.2}}</a>
            <br>
            <br>
            {% endif %}
        </div>
            {% if attr != 'nbc' %}
        <strong>{{adjs.5|title}} Words with Weights:</strong>
        <br>
        {% get_explanations classifier 2 True dec as wordlist%}
        {% for word in wordlist %}
        {{forloop.counter}}) {{word.0}}, {{word.1}}
        <br>
        {% endfor %}
            {% endif %}
        <br>
        <strong>{{adjs.5|title}} Tweets:</strong>
        <br>
        {% order_and_return classifier 5 as tweet_list %}
        {% for tweet in tweet_list|slice:"-5:" reversed %}
        {% autoescape off %}
        {% add_tag tweet.0 tweet.1 'strong' as to_print%}
        {{forloop.counter}}) {{to_print}}
        {% endautoescape %}
        <br>
        {% endfor %}
        <br>
        <br>
            {% if attr != 'nbc' %}
        <a class="page_button" href="{% url 'twitter:lex_edit' username attr adjs.1 %}">Make my profile {{adjs.3}}</a>
        <br>
        <br>
            {% else %}
            <a class="page_button" href="{% url 'twitter:lime_edit' username attr adjs.1 %}">Make my profile {{adjs.3}}</a>
            {% endif %}
    </div>
    <br>
    <br>
    <br>
    <a class="page_button" href="{% url 'twitter:profile' username%}">Take me back to my profiles</a>
</body>

mockingbird/twitter/templates/twitter/clf_info.html
<head>
    {% load static %}
    {% load multifor %}
    {% load twitter_tags %}
    <link rel="stylesheet" type="text/css" href="/static/twitter/style.css?{% now 'U' %}">
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js"></script>
    {{script|safe}}
</head>
<body>

    <div><strong>{{attr|title}} ({{classifier.classifier|title}})</strong></div>
    <br>
        <div class="lexicon">
        <div class="lex_column">
    {{paragraphs.0}}
    <br>
            <br>
        {{paragraphs.1}}
            </div>
    <div class="class_plot" align="center" style="font-size:5px;">{{ div|safe }}</div>
    </div>
    <br>
    <br>
    <strong>Your Predicted {{attr|capfirst}}: {{classifier.predicted_class|title}}</strong>
        <br>
        <br>
    <br>
    <a class="page_button" href="{% url 'twitter:profile' username%}">Take me back to my profiles</a>
    <br>
    <br>
    <span>Click this button to generate an explanation for your profile. This may take several minutes.</span>
    <a class="page_button" href="{% url 'twitter:lime_explain_all' username attr %}">Explain my profile</a>
    <br>
    <br>
    <br>
    <div style="font-size:16px;text-align:left;">
    {{paragraphs.2}}
    </div>
    <br>
            {% for a in adjs.0; b in adjs.1 %}
            <a class="page_button" href="{% url 'twitter:lime_edit' username attr a %}">Make my profile {{b}}</a>
            {% endfor %}
    <br>
    <br>
    <br>
    <br>
    <a class="page_button" href="{% url 'twitter:profile' username%}">Take me back to my profiles</a>
</body>

mockingbird/twitter/templates/twitter/lex_info.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="/static/twitter/style.css?{% now 'U' %}">
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js"></script>
    {{script|safe}}
    {% load twitter_tags %}
</head>
<body>
    <div><strong>{{name|capfirst}} Lexicon</strong></div>
    <br>
    <div class="lexicon">
        <div class="lex_column">
    {{paragraphs.0}}
    <br>
        {{paragraphs.1}}
            </div>
    <div class="class_plot" align="center" style="font-size:5px;">{{ div|safe }}</div>
    </div>
    <br>
    <br>
        <strong>Your Predicted {{attr|capfirst}}: {{classifier.predicted_class|title}}</strong>
        <br>
        <br>
    <a class="page_button" href="{% url 'twitter:profile' username%}">Take me back to my profiles</a>
    <br>
    <br>
    <br>
    <br>
    <div style="text-align:left;font-size:16px;">
        {{paragraphs.2}}
        </div>
    <br>
    <br>
    <div class="lex_exp">
        <div class="lex_column">
        <strong>{{adjs.4|title}} Words with Weights:</strong>
        <br>
        {% get_explanations classifier 1 True dec as wordlist%}
        {% for word in wordlist %}
        {{forloop.counter}}) {{word.0}}, {{word.1}}
        <br>
        {% endfor %}
        <br>
        <strong>{{adjs.4|title}} Tweets:</strong>
        <br>
        {% order_and_return classifier 2 as tweet_list %}
        {% for tweet in tweet_list|slice:":5" %}
            {% autoescape off %}
        {% add_tag tweet.0 tweet.1 'strong' as to_print%}
        {{forloop.counter}}) {{to_print}}
            {% endautoescape %}
        <br>
        {% endfor %}
        <br>
            <br>
        <br>
        <a class="page_button" href="{% url 'twitter:lex_edit' username attr adjs.0 %}">Make my profile {{adjs.2}}</a>
            <br>
            <br>
        </div>
        <strong>{{adjs.5|title}} Words with Weights:</strong>
        <br>
        {% get_explanations classifier 2 True dec as wordlist%}
        {% for word in wordlist %}
        {{forloop.counter}}) {{word.0}}, {{word.1}}
        <br>
        {% endfor %}
        <br>
        <strong>{{adjs.5|title}} Tweets:</strong>
        <br>
        {% order_and_return classifier 2 as tweet_list %}
        {% for tweet in tweet_list|slice:"-5:" reversed %}
        {% autoescape off %}
        {% add_tag tweet.0 tweet.1 'strong' as to_print%}
        {{forloop.counter}}) {{to_print}}
        {% endautoescape %}
        <br>
        {% endfor %}
        <br>
        <br>
        <a class="page_button" href="{% url 'twitter:lex_edit' username attr adjs.1 %}">Make my profile {{adjs.3}}</a>
        <br>
        <br>
    </div>
    <br>
    <br>
<a class="page_button" href="{% url 'twitter:profile' username%}">Take me back to my profiles</a>
</body>

mockingbird/twitter/templates/twitter/lime_explain_all.html
<head>
    {% load static %}
    {% load multifor %}
    {% load twitter_tags %}
    <link rel="stylesheet" type="text/css" href="/static/twitter/style.css?{% now 'U' %}">
    <script src="http://cdn.pydata.org/bokeh/release/bokeh-1.2.0.min.js"></script>
    {{script|safe}}
</head>
<body>
    <div><strong>Explanation</strong></div>
    <br>
    The following explanation is generated by LIME, a tool which determines how different words change the profile by
    removing them and seeing how the probabilities change. LIME <i>estimates</i> how the true classifier changes its
    results based on input and so may not always be perfectly accurate.
    <br>
    <br>
    {% if attr == 'nbc' %}
    <a class="page_button" href="{% url 'twitter:blob_info' username attr%}">Take me back to my profile</a>
    {% elif is_m3%}
    <a class="page_button" href="{% url 'twitter:m3_info' username attr%}">Take me back to my profile</a>
    {% else %}
    <a class="page_button" href="{% url 'twitter:clf_info' username attr%}">Take me back to my profile</a>
    {% endif %}
    <br>
    <br>
    <br>
    <div class="lime">
    {{exp | safe}}
        <br>
        <br>
        </div>
    <br>
    <br>
    <br>
</body>

mockingbird/twitter/templates/twitter/no_username.html
<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="/static/twitter/style.css?{% now 'U' %}">
</head>
<body>
    No results found for username @{{username}}
    <br>
    <br>
    <a class="page_button" href="{% url 'twitter:index'%}">Try again?</a>
</body>

mockingbird/twitter/templates/twitter/profile.html
<head>
    {% load static %}
    {% load twitter_tags %}
    <link rel="stylesheet" type="text/css" href="/static/twitter/style.css?{% now 'U' %}">
</head>

<body>
    <div><strong>We were able to generate the following profiles for you:</strong></div>
    <br>
    <br>
    <div class="tweet_list">
    {% for class in classes %}
        <h1 style="text-transform:capitalize;">{{class.0.attr_name}}</h1>
        <div class="profile" style="column-count:{{class|length}};">
        {% for classifier in class %}
            <div class="single_profile" style="break-after:column;font-size:16px;">
                {% if classifier.classifier != 'blob' %}
            <a style="text-transform:capitalize;"><strong>Classifier Type:</strong> {{classifier.classifier}}</a>
            <br>
                {% else %}
                <a style="text-transform:capitalize;"><strong>Classifier Type:</strong> {{classifier.extra_info}}</a>
            <br>
                {% endif %}
            <a style="text-transform:capitalize;"><strong>Predicted {{classifier.attr_name}}:</strong>
                {{classifier.predicted_class}}</a>
            <br>
            <a style="text-transform:capitalize;"><strong>Prediction Confidence:</strong>
                {{classifier.confidence_str}}</a>
            <br>
            {% if classifier.explanations != '' %}
                {% for c in classifier.get_class_descriptors %}
                <a style="text-transform:capitalize;"><strong>{{c}} Words:</strong>
                    <br>
                    {% get_explanations classifier forloop.counter False 0 as wordlist%}</a>
                    {% for word in wordlist %}
                    {{forloop.counter}}) {{word}}
                    <br>
                    {% endfor %}
                {% endfor %}
                {% endif %}
            <br>
            <br>
                {% if classifier.classifier == 'lexicon' %}
                <a class="page_button" href="{% url 'twitter:lex_info' username classifier.attr_name%}">Find Out More</a>
                {% elif classifier.classifier == 'm3' %}
                <a class="page_button" href="{% url 'twitter:m3_info' username classifier.attr_name%}">Find Out More</a>
                {% elif classifier.classifier == 'blob' %}
                    {% if classifier.extra_info == 'naive bayes classifier' %}
                    <a class="page_button" href="{% url 'twitter:blob_info' username 'nbc'%}">Find Out More</a>
                    {% elif classifier.attr_name == 'subjectivity' %}
                    <a class="page_button" href="{% url 'twitter:blob_info' username 'subjectivity'%}">Find Out More</a>
                    {% else %}
                    <a class="page_button" href="{% url 'twitter:blob_info' username 'polarity'%}">Find Out More</a>
                    {% endif %}
                {% elif classifier.extra_info == 'clf' %}
                    <a class="page_button" href="{% url 'twitter:clf_info' username classifier.attr_name%}">Find Out More</a>
                {% endif %}
                <br>
                <br>
            </div>
        {% endfor %}
        </div>
        <br>
        <br>
    {% endfor %}
    </div>

    <h1 style="text-transform:capitalize;text-align:left;">Big Five Personality</h1>
    <div style="text-transform:capitalize;text-align:left;font-size:16px;"><strong>Classifier Type:</strong>
        IBM Personality Insights</div>
    <div class="profile" style="text-align:left;">
            {% for class in ibm %}
            <a style="text-transform:capitalize;"><strong>Predicted {{class.attr_name}} Percentile:</strong>
                {{class.confidence_str}} ({{class.predicted_class}})</a>
            <br>
            {%endfor%}
        <br>
        <br>
        <a class="page_button" href="{% url 'twitter:ibm_info' username%}">Find Out More</a>
    </div>
    <br>
    <br>

<a class="page_button" href="{% url 'twitter:tweets' username%}">Take me to my Tweets</a>
<a class="page_button" href="{% url 'twitter:reset_tweets' username%}">Reset all Tweets</a>
</body>